export const FirstSection = {
  id: 'about',
  lightBackground: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Premium Bank',
  headline: 'Unlimited Transactions with zero fees',
  description: 'Get access to our exclusive lorem',
  buttonLabel: 'Get started',
  imageStart: false,
  img: '/images/loan-1.svg',
  alt: 'Car',
  dark: true,
  primary: true,
  darkText: false,
};

export const SecondSection = {
  id: 'discover',
  lightBackground: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Premium Bank',
  headline: 'Unlimited Transactions with zero fees',
  description: 'Get access to our exclusive lorem',
  buttonLabel: 'Get started',
  imageStart: true,
  img: '/images/loan-2.svg',
  alt: 'Car',
  dark: false,
  primary: false,
  darkText: true,
};

export const ThirdSection = {
  id: 'signup',
  lightBackground: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Premium Bank',
  headline: 'Unlimited Transactions with zero fees',
  description: 'Get access to our exclusive lorem',
  buttonLabel: 'Get started',
  imageStart: true,
  img: '/images/loan-3.svg',
  alt: 'Car',
  dark: true,
  primary: true,
  darkText: false,
};
